language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

branches:
  only:
  - master
  - develop

install:
  - sudo sudo apt-get install -y pylint
  - sudo pip install -U pytest

# command to run tests
script:
  - echo "pylint --errors-only src/logni.py ... "
  - pylint --errors-only src/logni.py

  - echo "pytest ... "
  - pytest

  - echo "run logni.py ... "
  - python src/logni.py

  - echo "run example.py ... "
  - python test/example/basic.py
