language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

env:
  - CODECOV_TOKEN="05aaf35c-89cb-419f-9012-e534e1248e3f"

branches:
  only:
  - master
  - develop

install:
  - sudo sudo apt-get install -y pylint
  - sudo pip install -U pytest
  - sudo pip install codecov

# command to run tests
script:
  - echo "pylint --errors-only src/*.py ... "
  - pylint --errors-only src/*.py

  - echo "pytest ... "
  - pytest
 
  - echo "example for utils ... "
  - python src/utilni.py

  - echo "example for filestream ... "
  - python src/filestream.py

  - echo "example for consolestream ... "
  - python src/consolestream.py

  - echo "run logni.py ... "
  - python src/logni.py

  - echo "run examples ... "
  - python test/example/basic.py

  - echo "codecov ... "
  - codecov --token=05aaf35c-89cb-419f-9012-e534e1248e3f

after_success:
  - codecov
