language: python
python:
  - "2.7"

branches:
  only:
  - master
  - develop

install:
  - sudo sudo apt-get install -y pylint

# command to run tests
script:
  - echo "pylint --errors-only src/logni.py ... "
  - pylint --errors-only src/logni.py

  - echo "run logni.py ... "
  - python src/logni.py

