language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

env:
  - CODECOV_TOKEN="05aaf35c-89cb-419f-9012-e534e1248e3f"

branches:
  only:
  - master
  - develop

install:
  - sudo sudo apt-get install -y pylint3 python3-pip python3-pytest python3
  - sudo pip3 install codecov

before_script:
  - export PYTHONPATH=$PYTHONPATH:$PWD

# command to run tests
script:
  - echo "pylint --errors-only logni/*.py ... "
  - pylint3 --errors-only logni/*.py

#  - echo "pytest ... "
#  - pytest-3
 
  - echo "example for utils ... "
  - python3 logni/utilni.py

#  - echo "example for filestream ... "
#  - python3 logni/filestream.py

  - echo "example for consolestream ... "
  - python3 logni/consolestream.py

#  - echo "run logni.py ... "
#  - python3 logni/logni.py

  - echo "run examples ... "
  - python3 test/example/basic_example.py

  - echo "codecov ... "
  - codecov --token=05aaf35c-89cb-419f-9012-e534e1248e3f

after_success:
  - codecov
